metadata:
  generateName: deploy-apps-
  namespace: argo
spec:
  entrypoint: starter
  arguments:
    parameters:
    - name: application-name-dev
      value: <APP_NAME> #CHANGE
    - name: application-name-stag
      value: <APP_NAME2> #CHANGE
    - name: revision
      value: <REVISION HASH> #CHANGE
    - name: argocd-server-address
      value: <SERVER ADDRESS> #CHANGE
    - name: argocd-credentials-secret
      value: argocd-user
  templates:
  - name: starter
    steps:
    - - name: deploy-to-dev
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: application-name
            value: "{{workflow.parameters.application-name-dev}}"
          - name: revision
            value: "{{workflow.parameters.revision}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.argocd-server-address}}"
    - - name: deploy-to-staging
        templateRef:
          name: argocd-step
          template: argocd-sync-and-wait
        arguments:
          parameters:
          - name: application-name
            value: "{{workflow.parameters.application-name-stag}}"
          - name: revision
            value: "{{workflow.parameters.revision}}"
          - name: argocd-server-address
            value: "{{workflow.parameters.argocd-server-address}}"
